-- Seed default amenities and rules for properties
-- This provides a comprehensive checklist of common property features

-- ============================================
-- AMENITIES
-- ============================================
-- Insert default amenities (if not already present)

INSERT INTO public.amenities (amenity_name) VALUES
  ('Wi-Fi'),
  ('High-Speed Internet'),
  ('Cable TV'),
  ('Smart TV'),
  ('Streaming Services'),
  ('Air Conditioning'),
  ('Heating'),
  ('Washer'),
  ('Dryer'),
  ('Dishwasher'),
  ('Microwave'),
  ('Refrigerator'),
  ('Oven/Stove'),
  ('Coffee Maker'),
  ('Toaster'),
  ('Blender'),
  ('Full Kitchen'),
  ('Kitchenette'),
  ('Dining Table'),
  ('Parking - Free'),
  ('Parking - Paid'),
  ('Garage Parking'),
  ('Street Parking'),
  ('EV Charger'),
  ('Swimming Pool'),
  ('Hot Tub / Jacuzzi'),
  ('Gym / Fitness Center'),
  ('Sauna'),
  ('Elevator'),
  ('Wheelchair Accessible'),
  ('Balcony'),
  ('Patio'),
  ('Garden'),
  ('BBQ Grill'),
  ('Outdoor Furniture'),
  ('Beach Access'),
  ('Lake Access'),
  ('Mountain View'),
  ('Ocean View'),
  ('City View'),
  ('Security System'),
  ('24/7 Security'),
  ('Smoke Detector'),
  ('Carbon Monoxide Detector'),
  ('Fire Extinguisher'),
  ('First Aid Kit'),
  ('Safe / Lock Box'),
  ('Doorman'),
  ('Concierge Service'),
  ('Room Service'),
  ('Daily Housekeeping'),
  ('Linens Provided'),
  ('Towels Provided'),
  ('Toiletries Provided'),
  ('Hair Dryer'),
  ('Iron & Ironing Board'),
  ('Hangers'),
  ('Luggage Storage'),
  ('Workspace / Desk'),
  ('Office Chair'),
  ('Printer'),
  ('Pet Friendly'),
  ('Pet Bowls'),
  ('Pet Bed'),
  ('Crib / Baby Bed'),
  ('High Chair'),
  ('Baby Safety Gates'),
  ('Board Games'),
  ('Books'),
  ('Gaming Console'),
  ('Bicycle Rentals'),
  ('Kayak / Canoe'),
  ('Tennis Court'),
  ('Basketball Court'),
  ('Golf Course Access'),
  ('Ski-in/Ski-out'),
  ('Storage Unit'),
  ('Mailbox Access'),
  ('Front Desk'),
  ('24-Hour Check-in'),
  ('Self Check-in'),
  ('Keyless Entry'),
  ('Pool Access Code'),
  ('Private Entrance'),
  ('Single-level Home'),
  ('Waterfront'),
  ('Fireplace'),
  ('Piano'),
  ('Sound System'),
  ('Outdoor Shower'),
  ('Outdoor Kitchen')
ON CONFLICT (amenity_name) DO NOTHING;

-- ============================================
-- RULES
-- ============================================
-- Insert default rules (if not already present)

INSERT INTO public.rules (rule_name) VALUES
  ('No Smoking'),
  ('No Smoking Indoors Only'),
  ('Smoking Allowed in Designated Areas'),
  ('No Pets'),
  ('Pets Allowed'),
  ('Pets Allowed with Fee'),
  ('Dogs Only'),
  ('Cats Only'),
  ('Small Pets Only'),
  ('Service Animals Welcome'),
  ('No Parties or Events'),
  ('Events Allowed with Approval'),
  ('Quiet Hours: 10 PM - 8 AM'),
  ('Quiet Hours: 11 PM - 7 AM'),
  ('No Loud Music After 10 PM'),
  ('Respect Neighbors'),
  ('Maximum Occupancy Enforced'),
  ('Children Welcome'),
  ('Adults Only (18+)'),
  ('Adults Only (21+)'),
  ('No Unregistered Guests'),
  ('Guest Registration Required'),
  ('Visitor Parking Pass Required'),
  ('Check-in: 3:00 PM'),
  ('Check-in: 4:00 PM'),
  ('Check-in: After 2:00 PM'),
  ('Flexible Check-in'),
  ('Early Check-in Available (Fee)'),
  ('Check-out: 10:00 AM'),
  ('Check-out: 11:00 AM'),
  ('Check-out: 12:00 PM (Noon)'),
  ('Late Check-out Available (Fee)'),
  ('Self Check-in Instructions Provided'),
  ('Take Off Shoes Indoors'),
  ('No Shoes on Carpet'),
  ('Dispose Trash Before Check-out'),
  ('Leave Property as Found'),
  ('Strip Beds Before Check-out'),
  ('Start Dishwasher Before Check-out'),
  ('Return Keys to Lockbox'),
  ('Return Keys to Front Desk'),
  ('Lock All Doors and Windows'),
  ('Turn Off All Lights'),
  ('Adjust Thermostat Before Leaving'),
  ('No Illegal Activities'),
  ('No Weapons'),
  ('Must be 25+ to Book'),
  ('Must be 21+ to Book'),
  ('Photo ID Required at Check-in'),
  ('Security Deposit Required'),
  ('Credit Card Authorization Required'),
  ('Damage Responsibility Agreement'),
  ('Lost Key Fee Applies'),
  ('Pool Hours: 8 AM - 10 PM'),
  ('Pool Use at Own Risk'),
  ('No Glass in Pool Area'),
  ('No Diving'),
  ('Adult Supervision Required for Children'),
  ('Hot Tub Temperature Limit'),
  ('Gym Use at Own Risk'),
  ('Beach/Lake Use at Own Risk'),
  ('BBQ Must Be Supervised'),
  ('No Open Flames on Balcony'),
  ('Dispose of Grill Ashes Properly'),
  ('Close Umbrella/Awning in Wind'),
  ('Parking Permit Required'),
  ('One Parking Space Per Unit'),
  ('Compact Cars Only'),
  ('No RV Parking'),
  ('No Boat Parking'),
  ('No Commercial Vehicles'),
  ('Register Vehicle with Front Desk'),
  ('Tow-Away Zone'),
  ('Fire Safety Rules Must Be Followed'),
  ('Emergency Exit Locations Noted'),
  ('No Candles or Incense'),
  ('Do Not Block Fire Exits'),
  ('Smoke Alarm Testing Prohibited'),
  ('Report Maintenance Issues Immediately'),
  ('No Alterations to Property'),
  ('No Nails/Screws in Walls'),
  ('Use Provided Furniture Protectors'),
  ('Internet Fair Use Policy'),
  ('No Streaming During Peak Hours'),
  ('TV Remote Batteries Responsibility'),
  ('Laundry Detergent Not Provided'),
  ('Energy Conservation Encouraged'),
  ('Recycle Where Possible'),
  ('Bring Your Own Toiletries'),
  ('Beach Toys Must Be Returned'),
  ('Respect Property Privacy Settings'),
  ('No Video/Audio Recording'),
  ('Security Camera Notice'),
  ('Beds Configuration Non-Negotiable'),
  ('No Moving Furniture'),
  ('Outdoor Furniture Stays Outdoors'),
  ('Close Windows During Rain'),
  ('Report Any Damage Within 24 Hours'),
  ('Extra Cleaning Fee for Excessive Mess'),
  ('Pet Cleanup Required Immediately'),
  ('No Pets on Furniture'),
  ('Keep Pets Leashed in Common Areas'),
  ('Notify Management of Early Departure'),
  ('No Refunds for Early Departure'),
  ('Cancellation Policy Applies'),
  ('Travel Insurance Recommended')
ON CONFLICT (rule_name) DO NOTHING;

-- ============================================
-- INDEXES for performance
-- ============================================

-- Create indexes for faster lookups (if not already present)
CREATE INDEX IF NOT EXISTS idx_amenities_name ON public.amenities(amenity_name);
CREATE INDEX IF NOT EXISTS idx_rules_name ON public.rules(rule_name);
CREATE INDEX IF NOT EXISTS idx_property_amenities_property ON public.property_amenities(property_id);
CREATE INDEX IF NOT EXISTS idx_property_amenities_amenity ON public.property_amenities(amenity_id);
CREATE INDEX IF NOT EXISTS idx_property_rules_property ON public.property_rules(property_id);
CREATE INDEX IF NOT EXISTS idx_property_rules_rule ON public.property_rules(rule_id);

-- ============================================
-- SUMMARY
-- ============================================
-- This migration seeds:
-- - 90+ default amenities covering common property features
-- - 100+ default rules covering policies, check-in/out, safety, and usage guidelines
--
-- These can now be selected as checkboxes when creating/editing properties
-- and will be displayed when viewing property details.
